version: '3'
services:
  # app:
  #   env_file:
  #     - .env
  #   container_name: app_container
  #   # restart: always
  #   build: .
  #   ports:
  #     - '$PORT:$PORT'
  #   links:
  #     - mysql
  #   environment:
  #     DB_HOST: mysql
  mysql:
    image: mysql
    container_name: db_container
    restart: always
    environment:
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
    ports:
      - '${DB_PORT}:3306'
    expose:
      - '3306'
    volumes:
      - mysql:/var/lib/mysql
    env_file:
      - .env

volumes:
  mysql:
    driver: local
